#!/usr/bin/env bash
# vinary-viewer installer (v0.2 — a standalone ClojureScript / Electron application, inspired by vmd).
#
#   • npm install + shadow-cljs release (builds the GUI dist/main/main.js + the terminal dist/cli, dist/tui)
#   • installs the `vv`/`vinary-viewer` launcher into $BIN (default ~/.local/bin) — one command, three modes:
#       vv [--gui] files…   GUI (default)      vv --cli file   terminal render      vv --tui file   terminal viewer
#   • migrates off the v0.1.0 vmd-patching tool (advisory — see below)
#
# Idempotent + re-runnable. Override with BIN=/some/dir and/or VV_BUILD=compile ./install.sh
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN="${BIN:-$HOME/.local/bin}"
# 'release' = optimized production build (:simple optimization — strips devtools + minifies; NOT
# :advanced, whose property-renaming breaks the re-frame / DataScript / remark interop). 'compile' = dev.
VV_BUILD="${VV_BUILD:-release}"

echo "==> vinary-viewer install (repo: $REPO)"
command -v npx >/dev/null 2>&1 || { echo "error: node/npx not found on PATH" >&2; exit 1; }

echo "==> npm install"
( cd "$REPO" && npm install --no-fund --no-audit )

echo "==> building GUI ($VV_BUILD)"
( cd "$REPO" && npx shadow-cljs "$VV_BUILD" main renderer )

echo "==> building terminal tools ($VV_BUILD:cli, $VV_BUILD:tui)"
# the :cli/:tui npm scripts also sync the tree-sitter grammars + graphics wasm the terminal renderer needs
( cd "$REPO" && npm run "${VV_BUILD}:cli" && npm run "${VV_BUILD}:tui" )

echo "==> installing launcher into $BIN"
mkdir -p "$BIN"
VERSION="$(node -p "require('$REPO/package.json').version" 2>/dev/null || echo unknown)"
# vinary-viewer is one command with three modes: GUI (default) | --cli | --tui. $REPO and $VERSION are baked in;
# runtime variables (\$@, \${1:-}, \$REPO) are escaped so they stay literal in the generated launcher.
cat > "$BIN/vinary-viewer" <<EOF
#!/usr/bin/env bash
# vinary-viewer launcher (generated by install.sh) — GUI (default) · --cli · --tui
REPO="$REPO"
case "\${1:-}" in
  --cli)        shift; exec node "\$REPO/dist/cli/vv-cli.js" "\$@" ;;
  --tui)        shift; exec node "\$REPO/dist/tui/vv-tui.js" "\$@" ;;
  --gui)        shift; exec "\$REPO/node_modules/.bin/electron" "\$REPO" "\$@" ;;
  -h|--help)    cat <<'USAGE'
vinary-viewer — preview Markdown, PDFs, images, diagrams & source

Usage:
  vv [--gui] [files…]   open in the desktop GUI (default), one tab per file/URL
  vv --cli  <file>      render a document to the terminal  (pipe-friendly:  vv --cli x.md | less)
  vv --tui  <file>      interactively page a document       (scroll · / find · t contents · q quit)
  vv --help | --version

Mode options:  vv --cli --help   ·   vv --tui --help
USAGE
                exit 0 ;;
  -V|--version) echo "vinary-viewer $VERSION" ;;
  *)            exec "\$REPO/node_modules/.bin/electron" "\$REPO" "\$@" ;;
esac
EOF
chmod +x "$BIN/vinary-viewer"
ln -sf "$BIN/vinary-viewer" "$BIN/vv"
echo "    vv [files…]    -> GUI (default)"
echo "    vv --cli FILE  -> render to the terminal"
echo "    vv --tui FILE  -> interactive terminal viewer"

# ---- migrate off v0.1.0 (the vmd-patching tool) -------------------------------------------------
# v0.1.0 patched the system `vmd` npm package, set ~/.vmdrc styles.extra, and installed a vmd() shell
# wrapper. This standalone app replaces all of that. We do NOT auto-edit your shell rc or the global
# vmd package; we detect the old install and tell you how to revert it. Your
# ~/.config/vinary-viewer/ (theme, keybindings.edn, grammars/) is preserved.
OLD_DEPLOY="$HOME/.local/share/vinary-viewer"
if [ -e "$OLD_DEPLOY/sidebar.js" ] || grep -qs 'vmd()' "$HOME/.bashrc" "$HOME/.zshrc" 2>/dev/null; then
  echo "==> NOTE: a v0.1.0 vmd-patching install was detected. To fully revert it, run:"
  echo "        git -C \"$REPO\" show v0.1.0:uninstall.sh | bash"
  echo "    and remove any 'vmd()' wrapper block from your ~/.bashrc / ~/.zshrc."
fi

case ":$PATH:" in *":$BIN:"*) : ;; *) echo "==> NOTE: add $BIN to your PATH" ;; esac
echo "==> done. Try:  vv README.md   ·   vv --cli README.md | less   ·   vv --tui README.md   ·   vv --help"
