#!/usr/bin/env bash
# vinary-viewer installer (v0.2 — a standalone ClojureScript / Electron application, inspired by vmd).
#
#   • npm install + shadow-cljs release (builds dist/main/main.js + resources/public/js)
#   • installs `vv` and `vinary-viewer` launchers into $BIN (default ~/.local/bin)
#   • migrates off the v0.1.0 vmd-patching tool (advisory — see below)
#
# Idempotent + re-runnable. Override with BIN=/some/dir and/or VV_BUILD=compile ./install.sh
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN="${BIN:-$HOME/.local/bin}"
# 'release' = optimized production build (:simple optimization — strips devtools + minifies; NOT
# :advanced, whose property-renaming breaks the re-frame / DataScript / remark interop). 'compile' = dev.
VV_BUILD="${VV_BUILD:-release}"

echo "==> vinary-viewer install (repo: $REPO)"
command -v npx >/dev/null 2>&1 || { echo "error: node/npx not found on PATH" >&2; exit 1; }

echo "==> npm install"
( cd "$REPO" && npm install --no-fund --no-audit )

echo "==> building ($VV_BUILD)"
( cd "$REPO" && npx shadow-cljs "$VV_BUILD" main renderer )

echo "==> installing launchers into $BIN"
mkdir -p "$BIN"
cat > "$BIN/vinary-viewer" <<EOF
#!/usr/bin/env bash
# vinary-viewer launcher (generated by install.sh)
exec "$REPO/node_modules/.bin/electron" "$REPO" "\$@"
EOF
chmod +x "$BIN/vinary-viewer"
ln -sf "$BIN/vinary-viewer" "$BIN/vv"
echo "    vv -> vinary-viewer -> electron $REPO"

# ---- migrate off v0.1.0 (the vmd-patching tool) -------------------------------------------------
# v0.1.0 patched the system `vmd` npm package, set ~/.vmdrc styles.extra, and installed a vmd() shell
# wrapper. This standalone app replaces all of that. We do NOT auto-edit your shell rc or the global
# vmd package; we detect the old install and tell you how to revert it. Your
# ~/.config/vinary-viewer/ (theme, keybindings.edn, grammars/) is preserved.
OLD_DEPLOY="$HOME/.local/share/vinary-viewer"
if [ -e "$OLD_DEPLOY/sidebar.js" ] || grep -qs 'vmd()' "$HOME/.bashrc" "$HOME/.zshrc" 2>/dev/null; then
  echo "==> NOTE: a v0.1.0 vmd-patching install was detected. To fully revert it, run:"
  echo "        git -C \"$REPO\" show v0.1.0:uninstall.sh | bash"
  echo "    and remove any 'vmd()' wrapper block from your ~/.bashrc / ~/.zshrc."
fi

case ":$PATH:" in *":$BIN:"*) : ;; *) echo "==> NOTE: add $BIN to your PATH" ;; esac
echo "==> done. Try:  vv README.md"
