/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 21
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_DOT = 2,
  anon_sym_COLON_COLON_EQ = 3,
  anon_sym_SEMI = 4,
  sym_keyword = 5,
  sym_string = 6,
  sym_char = 7,
  sym_number = 8,
  sym_operator = 9,
  sym_punctuation = 10,
  sym_comment = 11,
  sym_source_file = 12,
  sym_rule = 13,
  sym_declaration = 14,
  sym__item = 15,
  aux_sym_source_file_repeat1 = 16,
  aux_sym_rule_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_DOT] = ".",
  [anon_sym_COLON_COLON_EQ] = "::=",
  [anon_sym_SEMI] = ";",
  [sym_keyword] = "keyword",
  [sym_string] = "string",
  [sym_char] = "char",
  [sym_number] = "number",
  [sym_operator] = "operator",
  [sym_punctuation] = "punctuation",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_rule] = "rule",
  [sym_declaration] = "declaration",
  [sym__item] = "_item",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_rule_repeat1] = "rule_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COLON_COLON_EQ] = anon_sym_COLON_COLON_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_keyword] = sym_keyword,
  [sym_string] = sym_string,
  [sym_char] = sym_char,
  [sym_number] = sym_number,
  [sym_operator] = sym_operator,
  [sym_punctuation] = sym_punctuation,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_rule] = sym_rule,
  [sym_declaration] = sym_declaration,
  [sym__item] = sym__item,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_rule_repeat1] = aux_sym_rule_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_category = 1,
  field_keyword = 2,
  field_label = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_category] = "category",
  [field_keyword] = "keyword",
  [field_label] = "label",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_keyword, 0},
  [1] =
    {field_category, 0},
  [2] =
    {field_category, 2},
    {field_label, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(3);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == ';') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '?' ||
          lookahead == '|') ADVANCE(23);
      if (('(' <= lookahead && lookahead <= ',') ||
          lookahead == '[' ||
          lookahead == ']' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(3);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == ';') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '?' ||
          lookahead == '|') ADVANCE(23);
      if (('(' <= lookahead && lookahead <= '.') ||
          lookahead == '[' ||
          lookahead == ']' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(26);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(26);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(25);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON_COLON_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'c', 1,
        'd', 2,
        'e', 3,
        'i', 4,
        'l', 5,
        'n', 6,
        'p', 7,
        'r', 8,
        's', 9,
        't', 10,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(19);
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(21);
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead == 'm') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 15:
      if (lookahead == 'y') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(30);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(32);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 22:
      if (lookahead == 'k') ADVANCE(35);
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(38);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(42);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(46);
      END_STATE();
    case 33:
      if (lookahead == 'p') ADVANCE(47);
      END_STATE();
    case 34:
      if (lookahead == 'm') ADVANCE(48);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 37:
      if (lookahead == 'c') ADVANCE(51);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(53);
      END_STATE();
    case 40:
      if (lookahead == 'y') ADVANCE(54);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(55);
      END_STATE();
    case 42:
      if (lookahead == 'u') ADVANCE(56);
      END_STATE();
    case 43:
      if (lookahead == 'm') ADVANCE(57);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(47);
      END_STATE();
    case 46:
      if (lookahead == 'r') ADVANCE(59);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_keyword);
      END_STATE();
    case 48:
      if (lookahead == 'i') ADVANCE(60);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(62);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(63);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 54:
      if (lookahead == 'p') ADVANCE(64);
      END_STATE();
    case 55:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 56:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 57:
      if (lookahead == 'p') ADVANCE(66);
      END_STATE();
    case 58:
      if (lookahead == 'i') ADVANCE(67);
      END_STATE();
    case 59:
      if (lookahead == 'a') ADVANCE(68);
      END_STATE();
    case 60:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 61:
      if (lookahead == 'v') ADVANCE(70);
      END_STATE();
    case 62:
      if (lookahead == 'o') ADVANCE(71);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 64:
      if (lookahead == 'o') ADVANCE(72);
      END_STATE();
    case 65:
      if (lookahead == 'a') ADVANCE(73);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 67:
      if (lookahead == 'o') ADVANCE(75);
      END_STATE();
    case 68:
      if (lookahead == 't') ADVANCE(76);
      END_STATE();
    case 69:
      if (lookahead == 'a') ADVANCE(77);
      END_STATE();
    case 70:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 71:
      if (lookahead == 'n') ADVANCE(79);
      END_STATE();
    case 72:
      if (lookahead == 'i') ADVANCE(80);
      END_STATE();
    case 73:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 74:
      if (lookahead == 'y') ADVANCE(47);
      END_STATE();
    case 75:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 76:
      if (lookahead == 'o') ADVANCE(81);
      END_STATE();
    case 77:
      if (lookahead == 't') ADVANCE(82);
      END_STATE();
    case 78:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 79:
      if (lookahead == 's') ADVANCE(47);
      END_STATE();
    case 80:
      if (lookahead == 'n') ADVANCE(83);
      END_STATE();
    case 81:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 82:
      if (lookahead == 'o') ADVANCE(84);
      END_STATE();
    case 83:
      if (lookahead == 't') ADVANCE(85);
      END_STATE();
    case 84:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 85:
      if (lookahead == 's') ADVANCE(47);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLON_COLON_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_rule] = STATE(9),
    [sym_declaration] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_keyword] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__item] = STATE(3),
    [aux_sym_rule_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(13),
    [sym_keyword] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [sym_char] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [sym_operator] = ACTIONS(15),
    [sym_punctuation] = ACTIONS(11),
    [sym_comment] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym__item] = STATE(5),
    [aux_sym_rule_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(19),
    [sym_keyword] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [sym_char] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_operator] = ACTIONS(21),
    [sym_punctuation] = ACTIONS(17),
    [sym_comment] = ACTIONS(21),
  },
  [STATE(4)] = {
    [sym__item] = STATE(6),
    [aux_sym_rule_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_SEMI] = ACTIONS(25),
    [sym_keyword] = ACTIONS(27),
    [sym_string] = ACTIONS(27),
    [sym_char] = ACTIONS(27),
    [sym_number] = ACTIONS(27),
    [sym_operator] = ACTIONS(27),
    [sym_punctuation] = ACTIONS(23),
    [sym_comment] = ACTIONS(27),
  },
  [STATE(5)] = {
    [sym__item] = STATE(5),
    [aux_sym_rule_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(32),
    [sym_keyword] = ACTIONS(34),
    [sym_string] = ACTIONS(34),
    [sym_char] = ACTIONS(34),
    [sym_number] = ACTIONS(34),
    [sym_operator] = ACTIONS(34),
    [sym_punctuation] = ACTIONS(29),
    [sym_comment] = ACTIONS(34),
  },
  [STATE(6)] = {
    [sym__item] = STATE(5),
    [aux_sym_rule_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(37),
    [sym_keyword] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [sym_char] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_operator] = ACTIONS(21),
    [sym_punctuation] = ACTIONS(17),
    [sym_comment] = ACTIONS(21),
  },
  [STATE(7)] = {
    [sym__item] = STATE(8),
    [aux_sym_rule_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_SEMI] = ACTIONS(41),
    [sym_keyword] = ACTIONS(43),
    [sym_string] = ACTIONS(43),
    [sym_char] = ACTIONS(43),
    [sym_number] = ACTIONS(43),
    [sym_operator] = ACTIONS(43),
    [sym_punctuation] = ACTIONS(39),
    [sym_comment] = ACTIONS(43),
  },
  [STATE(8)] = {
    [sym__item] = STATE(5),
    [aux_sym_rule_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(45),
    [sym_keyword] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [sym_char] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_operator] = ACTIONS(21),
    [sym_punctuation] = ACTIONS(17),
    [sym_comment] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      sym_keyword,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      sym_comment,
    STATE(10), 3,
      sym_rule,
      sym_declaration,
      aux_sym_source_file_repeat1,
  [18] = 5,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      sym_identifier,
    ACTIONS(56), 1,
      sym_keyword,
    ACTIONS(59), 1,
      sym_comment,
    STATE(10), 3,
      sym_rule,
      sym_declaration,
      aux_sym_source_file_repeat1,
  [36] = 2,
    ACTIONS(64), 1,
      sym_identifier,
    ACTIONS(62), 3,
      ts_builtin_sym_end,
      sym_keyword,
      sym_comment,
  [45] = 2,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(66), 3,
      ts_builtin_sym_end,
      sym_keyword,
      sym_comment,
  [54] = 2,
    ACTIONS(72), 1,
      sym_identifier,
    ACTIONS(70), 3,
      ts_builtin_sym_end,
      sym_keyword,
      sym_comment,
  [63] = 2,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(74), 3,
      ts_builtin_sym_end,
      sym_keyword,
      sym_comment,
  [72] = 2,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(78), 3,
      ts_builtin_sym_end,
      sym_keyword,
      sym_comment,
  [81] = 2,
    ACTIONS(84), 1,
      sym_identifier,
    ACTIONS(82), 3,
      ts_builtin_sym_end,
      sym_keyword,
      sym_comment,
  [90] = 2,
    ACTIONS(86), 1,
      anon_sym_DOT,
    ACTIONS(88), 1,
      anon_sym_COLON_COLON_EQ,
  [97] = 1,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
  [101] = 1,
    ACTIONS(92), 1,
      sym_identifier,
  [105] = 1,
    ACTIONS(94), 1,
      anon_sym_COLON_COLON_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 18,
  [SMALL_STATE(11)] = 36,
  [SMALL_STATE(12)] = 45,
  [SMALL_STATE(13)] = 54,
  [SMALL_STATE(14)] = 63,
  [SMALL_STATE(15)] = 72,
  [SMALL_STATE(16)] = 81,
  [SMALL_STATE(17)] = 90,
  [SMALL_STATE(18)] = 97,
  [SMALL_STATE(19)] = 101,
  [SMALL_STATE(20)] = 105,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 2, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 2, 0, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 1),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 3, 0, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3, 0, 2),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 3, 0, 2),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 5, 0, 3),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 5, 0, 3),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 2),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 4, 0, 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 6, 0, 3),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 6, 0, 3),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [90] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bnfc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bnfc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
