#!/usr/bin/env node
'use strict';

// Vendor static UI assets (Font Awesome + self-hosted fonts) from node_modules
// into resources/public/assets/ so the app ships them locally (offline, no CDN,
// CSP-friendly). Idempotent: only rewrites a destination when its bytes differ,
// and records every vendored file (package version + sha256) in
// scripts/assets.lock.json for reproducibility. Runs as part of the build
// (see the `assets:sync` npm script); upgrades are a dependency bump + rebuild.
//
// Mirrors the grammar-vendoring workflow (scripts/sync-grammars.mjs). Keep the
// MANIFEST below in sync with resources/public/assets/fonts/fonts.css — the
// @font-face `src` paths there must match the font `to` paths here.

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import crypto from 'node:crypto';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const assetsRoot = path.join(root, 'resources', 'public', 'assets');
const lockPath = path.join(root, 'scripts', 'assets.lock.json');

const MANIFEST = [
  // Font Awesome Free 7 — core CSS (icon glyph map + base classes), the Solid
  // style CSS (@font-face + .fa-solid), and the Solid webfont it references.
  { pkg: '@fortawesome/fontawesome-free', from: 'css/fontawesome.min.css',     to: 'fa/css/fontawesome.min.css' },
  { pkg: '@fortawesome/fontawesome-free', from: 'css/solid.min.css',           to: 'fa/css/solid.min.css' },
  { pkg: '@fortawesome/fontawesome-free', from: 'webfonts/fa-solid-900.woff2', to: 'fa/webfonts/fa-solid-900.woff2' },
  // Fira Code (variable weight) — code / monospace face. Latin + Latin-Extended.
  // (Noto Sans — UI / body / Markdown — is no longer synced here: it is hand-vendored as full-coverage
  //  OTF under resources/public/assets/fonts/noto-sans-otf/ and git-tracked, like lm-roman. See ADR-0011.)
  { pkg: '@fontsource-variable/fira-code', from: 'files/fira-code-latin-wght-normal.woff2',     to: 'fonts/fira-code/fira-code-latin-wght-normal.woff2' },
  { pkg: '@fontsource-variable/fira-code', from: 'files/fira-code-latin-ext-wght-normal.woff2', to: 'fonts/fira-code/fira-code-latin-ext-wght-normal.woff2' }
];

function ensureDir(dir) { fs.mkdirSync(dir, { recursive: true }); }
function sha256(buf) { return crypto.createHash('sha256').update(buf).digest('hex'); }

function pkgDir(pkg) {
  return path.dirname(require.resolve(`${pkg}/package.json`));
}

const versionCache = {};
function pkgVersion(pkg) {
  if (!(pkg in versionCache)) {
    versionCache[pkg] = JSON.parse(fs.readFileSync(path.join(pkgDir(pkg), 'package.json'), 'utf8')).version;
  }
  return versionCache[pkg];
}

let copied = 0;
let unchanged = 0;
const lockFiles = [];

for (const item of MANIFEST) {
  const src = path.join(pkgDir(item.pkg), item.from);
  if (!fs.existsSync(src)) {
    console.error(`✗ missing source: ${item.pkg}/${item.from}`);
    console.error('  run `npm install` (the dev dependency may be missing or a different version) and retry.');
    process.exit(1);
  }
  const buf = fs.readFileSync(src);
  const hash = sha256(buf);
  const dest = path.join(assetsRoot, item.to);
  const fresh = fs.existsSync(dest) && sha256(fs.readFileSync(dest)) === hash;
  if (fresh) {
    unchanged++;
  } else {
    ensureDir(path.dirname(dest));
    fs.writeFileSync(dest, buf);
    copied++;
    console.log(`+ ${item.to}  (${item.pkg}@${pkgVersion(item.pkg)})`);
  }
  lockFiles.push({ to: item.to, pkg: item.pkg, from: item.from, bytes: buf.length, sha256: hash });
}

const packages = {};
for (const item of MANIFEST) packages[item.pkg] = pkgVersion(item.pkg);

const lock = {
  comment: 'Generated by scripts/sync-assets.mjs — DO NOT EDIT. Regenerate with `npm run assets:sync`.',
  packages,
  files: lockFiles
};
fs.writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`);

console.log(`\nvendored ${MANIFEST.length} asset(s): ${copied} copied, ${unchanged} unchanged → ${path.relative(root, assetsRoot)}/`);
console.log(`wrote ${path.relative(root, lockPath)}`);
