#!/usr/bin/env node
'use strict';

// Vendor the PDF.js worker + data assets (cmaps, standard_fonts, wasm, iccs) from
// node_modules/pdfjs-dist into resources/public/pdf/ so the sandboxed renderer loads
// them app-relative from file:// (offline, no CDN, CSP/sandbox-friendly). Idempotent:
// only rewrites a destination when its bytes differ, and records every vendored file
// (version + sha256) in scripts/pdfjs.lock.json for reproducibility. Runs as part of
// the build (the `pdfjs:sync` npm script); upgrades are a dependency bump + rebuild.
//
// The worker file MUST be byte-version-matched to the pdfjs-dist main module (pdf.js
// refuses a mismatched worker), so this fails loudly if the installed pdfjs-dist
// version differs from the version pinned in package.json.
//
// Mirrors scripts/sync-assets.mjs / scripts/sync-grammars.mjs.

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import crypto from 'node:crypto';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const pdfOutRoot = path.join(root, 'resources', 'public', 'pdf');
const lockPath = path.join(root, 'scripts', 'pdfjs.lock.json');

const pkgDir = path.dirname(require.resolve('pdfjs-dist/package.json'));
const installedVersion = JSON.parse(fs.readFileSync(path.join(pkgDir, 'package.json'), 'utf8')).version;
const pinnedVersion = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).dependencies['pdfjs-dist'];

// worker-mismatch guard: the vendored worker must match the main module byte-for-byte
if (installedVersion !== pinnedVersion) {
  console.error(`✗ pdfjs-dist version mismatch: installed ${installedVersion} != package.json pin ${pinnedVersion}`);
  console.error('  run `npm install` to align, or bump the pin + re-run `npm run pdfjs:sync`.');
  process.exit(1);
}

// What to vendor: the LEGACY (ES5-friendly) main module + its byte-matched worker, plus the four data
// directories. We vendor the *legacy* build because the modern build's dynamic import() cannot be
// bundled by Closure :simple; the module is loaded at runtime via native ESM import() (see
// vinary.renderer.pdf), so it never goes through Closure.
const FILES = [
  { from: 'legacy/build/pdf.min.mjs',        to: 'pdf.min.mjs' },         // main module (runtime import)
  { from: 'legacy/build/pdf.worker.min.mjs', to: 'pdf.worker.min.mjs' },  // worker (byte-matched to the module)
];
const DIRS = ['cmaps', 'standard_fonts', 'wasm', 'iccs'];

function ensureDir(dir) { fs.mkdirSync(dir, { recursive: true }); }
function sha256(buf) { return crypto.createHash('sha256').update(buf).digest('hex'); }

let copied = 0;
let unchanged = 0;
const lockFiles = [];

function vendorFile(srcAbs, toRel) {
  const buf = fs.readFileSync(srcAbs);
  const hash = sha256(buf);
  const dest = path.join(pdfOutRoot, toRel);
  if (fs.existsSync(dest) && sha256(fs.readFileSync(dest)) === hash) {
    unchanged++;
  } else {
    ensureDir(path.dirname(dest));
    fs.writeFileSync(dest, buf);
    copied++;
  }
  lockFiles.push({ to: toRel, bytes: buf.length, sha256: hash });
}

function vendorDir(dirName) {
  const srcRoot = path.join(pkgDir, dirName);
  if (!fs.existsSync(srcRoot)) {
    console.error(`✗ missing source dir: pdfjs-dist/${dirName}`);
    process.exit(1);
  }
  const walk = (cur) => {
    for (const name of fs.readdirSync(cur).sort()) {
      const child = path.join(cur, name);
      if (fs.statSync(child).isDirectory()) walk(child);
      else vendorFile(child, path.posix.join(dirName, path.relative(srcRoot, child).split(path.sep).join('/')));
    }
  };
  walk(srcRoot);
}

for (const f of FILES) {
  const src = path.join(pkgDir, f.from);
  if (!fs.existsSync(src)) {
    console.error(`✗ missing source: pdfjs-dist/${f.from}`);
    process.exit(1);
  }
  vendorFile(src, f.to);
}
for (const d of DIRS) vendorDir(d);

lockFiles.sort((a, b) => a.to.localeCompare(b.to));
const lock = {
  comment: 'Generated by scripts/sync-pdfjs.mjs — DO NOT EDIT. Regenerate with `npm run pdfjs:sync`.',
  package: 'pdfjs-dist',
  version: installedVersion,
  files: lockFiles
};
fs.writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`);

console.log(`vendored ${lockFiles.length} pdf.js file(s): ${copied} copied, ${unchanged} unchanged → ${path.relative(root, pdfOutRoot)}/`);
console.log(`wrote ${path.relative(root, lockPath)} (pdfjs-dist@${installedVersion})`);
