/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_COLON = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_DOT = 5,
  sym_comment = 6,
  aux_sym_string_token1 = 7,
  aux_sym_string_token2 = 8,
  sym_block_string = 9,
  sym_number = 10,
  anon_sym_true = 11,
  anon_sym_false = 12,
  sym_null = 13,
  sym_reserved_word = 14,
  sym_arrow_operator = 15,
  sym_unquoted_text = 16,
  sym__newline = 17,
  sym_source_file = 18,
  sym__statement = 19,
  sym_block = 20,
  sym_assignment = 21,
  sym_edge = 22,
  sym__path = 23,
  sym__path_segment = 24,
  aux_sym__value = 25,
  sym_string = 26,
  sym_boolean = 27,
  aux_sym_source_file_repeat1 = 28,
  aux_sym__path_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOT] = ".",
  [sym_comment] = "comment",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym_block_string] = "block_string",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [sym_reserved_word] = "reserved_word",
  [sym_arrow_operator] = "arrow_operator",
  [sym_unquoted_text] = "unquoted_text",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_block] = "block",
  [sym_assignment] = "assignment",
  [sym_edge] = "edge",
  [sym__path] = "_path",
  [sym__path_segment] = "_path_segment",
  [aux_sym__value] = "_value",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__path_repeat1] = "_path_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_comment] = sym_comment,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_block_string] = sym_block_string,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [sym_reserved_word] = sym_reserved_word,
  [sym_arrow_operator] = sym_arrow_operator,
  [sym_unquoted_text] = sym_unquoted_text,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_block] = sym_block,
  [sym_assignment] = sym_assignment,
  [sym_edge] = sym_edge,
  [sym__path] = sym__path,
  [sym__path_segment] = sym__path_segment,
  [aux_sym__value] = aux_sym__value,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__path_repeat1] = aux_sym__path_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_block_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_reserved_word] = {
    .visible = true,
    .named = true,
  },
  [sym_arrow_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_text] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_edge] = {
    .visible = true,
    .named = true,
  },
  [sym__path] = {
    .visible = false,
    .named = true,
  },
  [sym__path_segment] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__value] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__path_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_operator = 2,
  field_source = 3,
  field_target = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_operator] = "operator",
  [field_source] = "source",
  [field_target] = "target",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
  [1] =
    {field_operator, 1},
    {field_source, 0},
    {field_target, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 11,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '\n', 51,
        '"', 1,
        '#', 21,
        '\'', 2,
        '+', 10,
        '-', 3,
        '.', 20,
        ':', 17,
        '<', 4,
        '=', 5,
        '{', 18,
        '|', 6,
        '}', 19,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '>') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(37);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 6:
      if (lookahead == '|') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == '|') ADVANCE(26);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '|') ADVANCE(26);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '\n', 51,
        '"', 39,
        '#', 21,
        '\'', 40,
        '{', 18,
        '|', 41,
        '}', 19,
        '+', 47,
        '-', 47,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < '0' || ';' < lookahead)) ADVANCE(50);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != ':' &&
          lookahead != ';' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != ':' &&
          lookahead != ';' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_block_string);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_block_string);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != ':' &&
          lookahead != ';' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(48);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          (lookahead < '0' || ';' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          (lookahead < '0' || ';' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          (lookahead < '0' || ';' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          (lookahead < '0' || ';' < lookahead) &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_arrow_operator);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_arrow_operator);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_arrow_operator);
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_unquoted_text);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == ':' ||
          lookahead == ';' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_unquoted_text);
      if (lookahead == '\'') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(46);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == ':' ||
          lookahead == ';' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_unquoted_text);
      if (lookahead == '|') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == ':' ||
          lookahead == ';' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_unquoted_text);
      if (lookahead == '|') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == ':' ||
          lookahead == ';' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(8);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_unquoted_text);
      if (lookahead == '|') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == ':' ||
          lookahead == ';' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(8);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_unquoted_text);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          (lookahead < '0' || ';' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_unquoted_text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == ':' ||
          lookahead == ';' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(39);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_unquoted_text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '#' ||
          lookahead == ':' ||
          lookahead == ';' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(40);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_unquoted_text);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          (lookahead < '0' || ';' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_unquoted_text);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          (lookahead < '0' || ';' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_unquoted_text);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          (lookahead < '0' || ';' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_unquoted_text);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != ':' &&
          lookahead != ';' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(51);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'f', 5,
        'h', 6,
        'i', 7,
        'l', 8,
        'n', 9,
        'o', 10,
        's', 11,
        't', 12,
        'v', 13,
        'w', 14,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == '2') ADVANCE(19);
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(25);
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(27);
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(29);
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead == 'p') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'h') ADVANCE(32);
      if (lookahead == 'o') ADVANCE(33);
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(35);
      if (lookahead == 'o') ADVANCE(36);
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(41);
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 19:
      if (lookahead == '-') ADVANCE(45);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(48);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(51);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 27:
      if (lookahead == 'b') ADVANCE(53);
      if (lookahead == 'y') ADVANCE(54);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(57);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(58);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(59);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(60);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(61);
      if (lookahead == 'y') ADVANCE(62);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(63);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(65);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(66);
      END_STATE();
    case 39:
      if (lookahead == 'd') ADVANCE(67);
      END_STATE();
    case 40:
      if (lookahead == 'm') ADVANCE(68);
      END_STATE();
    case 41:
      if (lookahead == 'd') ADVANCE(69);
      END_STATE();
    case 42:
      if (lookahead == 'd') ADVANCE(70);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(71);
      END_STATE();
    case 44:
      if (lookahead == 's') ADVANCE(72);
      END_STATE();
    case 45:
      if (lookahead == 'c') ADVANCE(73);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 47:
      if (lookahead == 's') ADVANCE(75);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(76);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(77);
      END_STATE();
    case 50:
      if (lookahead == 'g') ADVANCE(78);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 52:
      if (lookahead == 'l') ADVANCE(79);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 54:
      if (lookahead == 'o') ADVANCE(81);
      END_STATE();
    case 55:
      if (lookahead == 'k') ADVANCE(69);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(69);
      END_STATE();
    case 57:
      if (lookahead == 'l') ADVANCE(82);
      END_STATE();
    case 58:
      if (lookahead == 'c') ADVANCE(83);
      END_STATE();
    case 59:
      if (lookahead == 'd') ADVANCE(84);
      if (lookahead == 'p') ADVANCE(85);
      END_STATE();
    case 60:
      if (lookahead == 'r') ADVANCE(86);
      END_STATE();
    case 61:
      if (lookahead == 'o') ADVANCE(87);
      END_STATE();
    case 62:
      if (lookahead == 'l') ADVANCE(88);
      END_STATE();
    case 63:
      if (lookahead == 'g') ADVANCE(89);
      END_STATE();
    case 64:
      if (lookahead == 'l') ADVANCE(90);
      END_STATE();
    case 65:
      if (lookahead == 'e') ADVANCE(91);
      END_STATE();
    case 66:
      if (lookahead == 's') ADVANCE(69);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(92);
      END_STATE();
    case 68:
      if (lookahead == 'a') ADVANCE(93);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_reserved_word);
      END_STATE();
    case 70:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 71:
      if (lookahead == 's') ADVANCE(95);
      END_STATE();
    case 72:
      if (lookahead == 't') ADVANCE(96);
      END_STATE();
    case 73:
      if (lookahead == 'o') ADVANCE(97);
      END_STATE();
    case 74:
      if (lookahead == 'c') ADVANCE(98);
      END_STATE();
    case 75:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_reserved_word);
      if (lookahead == 'e') ADVANCE(100);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_reserved_word);
      if (lookahead == '-') ADVANCE(101);
      END_STATE();
    case 78:
      if (lookahead == 'h') ADVANCE(102);
      END_STATE();
    case 79:
      if (lookahead == 'i') ADVANCE(103);
      END_STATE();
    case 80:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 81:
      if (lookahead == 'u') ADVANCE(104);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 83:
      if (lookahead == 'i') ADVANCE(105);
      END_STATE();
    case 84:
      if (lookahead == 'o') ADVANCE(106);
      END_STATE();
    case 85:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 86:
      if (lookahead == 'c') ADVANCE(107);
      END_STATE();
    case 87:
      if (lookahead == 'k') ADVANCE(108);
      END_STATE();
    case 88:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 89:
      if (lookahead == 'e') ADVANCE(109);
      END_STATE();
    case 90:
      if (lookahead == 't') ADVANCE(110);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 92:
      if (lookahead == 'h') ADVANCE(69);
      END_STATE();
    case 93:
      if (lookahead == 't') ADVANCE(111);
      END_STATE();
    case 94:
      if (lookahead == 'r') ADVANCE(112);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_reserved_word);
      if (lookahead == 'e') ADVANCE(113);
      END_STATE();
    case 96:
      if (lookahead == 'r') ADVANCE(114);
      END_STATE();
    case 97:
      if (lookahead == 'n') ADVANCE(115);
      END_STATE();
    case 98:
      if (lookahead == 't') ADVANCE(116);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 100:
      if (lookahead == 'd') ADVANCE(69);
      END_STATE();
    case 101:
      if (lookahead == 'c') ADVANCE(117);
      if (lookahead == 's') ADVANCE(118);
      END_STATE();
    case 102:
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 103:
      if (lookahead == 'c') ADVANCE(69);
      END_STATE();
    case 104:
      if (lookahead == 't') ADVANCE(119);
      END_STATE();
    case 105:
      if (lookahead == 't') ADVANCE(120);
      END_STATE();
    case 106:
      if (lookahead == 'w') ADVANCE(69);
      END_STATE();
    case 107:
      if (lookahead == 'e') ADVANCE(121);
      END_STATE();
    case 108:
      if (lookahead == 'e') ADVANCE(122);
      END_STATE();
    case 109:
      if (lookahead == 't') ADVANCE(123);
      END_STATE();
    case 110:
      if (lookahead == 'i') ADVANCE(124);
      END_STATE();
    case 111:
      if (lookahead == 'e') ADVANCE(125);
      END_STATE();
    case 112:
      if (lookahead == '-') ADVANCE(126);
      END_STATE();
    case 113:
      if (lookahead == 's') ADVANCE(69);
      END_STATE();
    case 114:
      if (lookahead == 'a') ADVANCE(127);
      END_STATE();
    case 115:
      if (lookahead == 'f') ADVANCE(128);
      END_STATE();
    case 116:
      if (lookahead == 'i') ADVANCE(129);
      END_STATE();
    case 117:
      if (lookahead == 'o') ADVANCE(130);
      END_STATE();
    case 118:
      if (lookahead == 'i') ADVANCE(131);
      END_STATE();
    case 119:
      if (lookahead == '-') ADVANCE(132);
      END_STATE();
    case 120:
      if (lookahead == 'y') ADVANCE(69);
      END_STATE();
    case 121:
      if (lookahead == '-') ADVANCE(133);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_reserved_word);
      if (lookahead == '-') ADVANCE(134);
      END_STATE();
    case 123:
      if (lookahead == '-') ADVANCE(135);
      END_STATE();
    case 124:
      if (lookahead == 'p') ADVANCE(69);
      END_STATE();
    case 125:
      if (lookahead == 'd') ADVANCE(69);
      END_STATE();
    case 126:
      if (lookahead == 'r') ADVANCE(136);
      END_STATE();
    case 127:
      if (lookahead == 'i') ADVANCE(137);
      END_STATE();
    case 128:
      if (lookahead == 'i') ADVANCE(138);
      END_STATE();
    case 129:
      if (lookahead == 'o') ADVANCE(139);
      END_STATE();
    case 130:
      if (lookahead == 'l') ADVANCE(140);
      END_STATE();
    case 131:
      if (lookahead == 'z') ADVANCE(141);
      END_STATE();
    case 132:
      if (lookahead == 'e') ADVANCE(142);
      END_STATE();
    case 133:
      if (lookahead == 'a') ADVANCE(143);
      END_STATE();
    case 134:
      if (lookahead == 'd') ADVANCE(144);
      if (lookahead == 'w') ADVANCE(145);
      END_STATE();
    case 135:
      if (lookahead == 'a') ADVANCE(146);
      END_STATE();
    case 136:
      if (lookahead == 'a') ADVANCE(147);
      END_STATE();
    case 137:
      if (lookahead == 'n') ADVANCE(148);
      END_STATE();
    case 138:
      if (lookahead == 'g') ADVANCE(69);
      END_STATE();
    case 139:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 140:
      if (lookahead == 'o') ADVANCE(149);
      END_STATE();
    case 141:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 142:
      if (lookahead == 'n') ADVANCE(150);
      END_STATE();
    case 143:
      if (lookahead == 'r') ADVANCE(151);
      END_STATE();
    case 144:
      if (lookahead == 'a') ADVANCE(152);
      END_STATE();
    case 145:
      if (lookahead == 'i') ADVANCE(153);
      END_STATE();
    case 146:
      if (lookahead == 'r') ADVANCE(154);
      END_STATE();
    case 147:
      if (lookahead == 'd') ADVANCE(155);
      END_STATE();
    case 148:
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 149:
      if (lookahead == 'r') ADVANCE(69);
      END_STATE();
    case 150:
      if (lookahead == 'g') ADVANCE(156);
      END_STATE();
    case 151:
      if (lookahead == 'r') ADVANCE(157);
      END_STATE();
    case 152:
      if (lookahead == 's') ADVANCE(158);
      END_STATE();
    case 153:
      if (lookahead == 'd') ADVANCE(159);
      END_STATE();
    case 154:
      if (lookahead == 'r') ADVANCE(160);
      END_STATE();
    case 155:
      if (lookahead == 'i') ADVANCE(161);
      END_STATE();
    case 156:
      if (lookahead == 'i') ADVANCE(162);
      END_STATE();
    case 157:
      if (lookahead == 'o') ADVANCE(163);
      END_STATE();
    case 158:
      if (lookahead == 'h') ADVANCE(69);
      END_STATE();
    case 159:
      if (lookahead == 't') ADVANCE(164);
      END_STATE();
    case 160:
      if (lookahead == 'o') ADVANCE(165);
      END_STATE();
    case 161:
      if (lookahead == 'u') ADVANCE(166);
      END_STATE();
    case 162:
      if (lookahead == 'n') ADVANCE(167);
      END_STATE();
    case 163:
      if (lookahead == 'w') ADVANCE(168);
      END_STATE();
    case 164:
      if (lookahead == 'h') ADVANCE(69);
      END_STATE();
    case 165:
      if (lookahead == 'w') ADVANCE(169);
      END_STATE();
    case 166:
      if (lookahead == 's') ADVANCE(69);
      END_STATE();
    case 167:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 168:
      if (lookahead == 'h') ADVANCE(170);
      END_STATE();
    case 169:
      if (lookahead == 'h') ADVANCE(171);
      END_STATE();
    case 170:
      if (lookahead == 'e') ADVANCE(172);
      END_STATE();
    case 171:
      if (lookahead == 'e') ADVANCE(173);
      END_STATE();
    case 172:
      if (lookahead == 'a') ADVANCE(174);
      END_STATE();
    case 173:
      if (lookahead == 'a') ADVANCE(175);
      END_STATE();
    case 174:
      if (lookahead == 'd') ADVANCE(69);
      END_STATE();
    case 175:
      if (lookahead == 'd') ADVANCE(69);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 15},
  [6] = {.lex_state = 15},
  [7] = {.lex_state = 15},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 15},
  [12] = {.lex_state = 15},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [sym_block_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_reserved_word] = ACTIONS(1),
    [sym_arrow_operator] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(24),
    [sym__statement] = STATE(8),
    [sym_block] = STATE(8),
    [sym_assignment] = STATE(8),
    [sym_edge] = STATE(8),
    [sym__path] = STATE(23),
    [sym__path_segment] = STATE(13),
    [sym_string] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [aux_sym_string_token1] = ACTIONS(9),
    [aux_sym_string_token2] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [sym_reserved_word] = ACTIONS(11),
    [sym__newline] = ACTIONS(7),
  },
  [STATE(2)] = {
    [aux_sym__value] = STATE(6),
    [sym_string] = STATE(6),
    [sym_boolean] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(13),
    [sym_comment] = ACTIONS(13),
    [aux_sym_string_token1] = ACTIONS(19),
    [aux_sym_string_token2] = ACTIONS(19),
    [sym_block_string] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(15),
    [sym_reserved_word] = ACTIONS(23),
    [sym_unquoted_text] = ACTIONS(15),
    [sym__newline] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(3),
    [sym_block] = STATE(3),
    [sym_assignment] = STATE(3),
    [sym_edge] = STATE(3),
    [sym__path] = STATE(23),
    [sym__path_segment] = STATE(13),
    [sym_string] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(25),
    [sym_comment] = ACTIONS(30),
    [aux_sym_string_token1] = ACTIONS(33),
    [aux_sym_string_token2] = ACTIONS(33),
    [sym_number] = ACTIONS(36),
    [sym_reserved_word] = ACTIONS(36),
    [sym__newline] = ACTIONS(30),
  },
  [STATE(4)] = {
    [aux_sym__value] = STATE(5),
    [sym_string] = STATE(5),
    [sym_boolean] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_identifier] = ACTIONS(41),
    [anon_sym_RBRACE] = ACTIONS(39),
    [sym_comment] = ACTIONS(39),
    [aux_sym_string_token1] = ACTIONS(41),
    [aux_sym_string_token2] = ACTIONS(41),
    [sym_block_string] = ACTIONS(43),
    [sym_number] = ACTIONS(41),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(43),
    [sym_reserved_word] = ACTIONS(39),
    [sym_unquoted_text] = ACTIONS(43),
    [sym__newline] = ACTIONS(39),
  },
  [STATE(5)] = {
    [aux_sym__value] = STATE(5),
    [sym_string] = STATE(5),
    [sym_boolean] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_identifier] = ACTIONS(47),
    [anon_sym_RBRACE] = ACTIONS(45),
    [sym_comment] = ACTIONS(45),
    [aux_sym_string_token1] = ACTIONS(50),
    [aux_sym_string_token2] = ACTIONS(50),
    [sym_block_string] = ACTIONS(47),
    [sym_number] = ACTIONS(47),
    [anon_sym_true] = ACTIONS(53),
    [anon_sym_false] = ACTIONS(53),
    [sym_null] = ACTIONS(47),
    [sym_reserved_word] = ACTIONS(56),
    [sym_unquoted_text] = ACTIONS(47),
    [sym__newline] = ACTIONS(45),
  },
  [STATE(6)] = {
    [aux_sym__value] = STATE(5),
    [sym_string] = STATE(5),
    [sym_boolean] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(59),
    [sym_comment] = ACTIONS(59),
    [aux_sym_string_token1] = ACTIONS(61),
    [aux_sym_string_token2] = ACTIONS(61),
    [sym_block_string] = ACTIONS(43),
    [sym_number] = ACTIONS(61),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(43),
    [sym_reserved_word] = ACTIONS(59),
    [sym_unquoted_text] = ACTIONS(43),
    [sym__newline] = ACTIONS(59),
  },
  [STATE(7)] = {
    [aux_sym__value] = STATE(4),
    [sym_string] = STATE(4),
    [sym_boolean] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(63),
    [sym_identifier] = ACTIONS(65),
    [anon_sym_RBRACE] = ACTIONS(63),
    [sym_comment] = ACTIONS(63),
    [aux_sym_string_token1] = ACTIONS(19),
    [aux_sym_string_token2] = ACTIONS(19),
    [sym_block_string] = ACTIONS(65),
    [sym_number] = ACTIONS(65),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(65),
    [sym_reserved_word] = ACTIONS(67),
    [sym_unquoted_text] = ACTIONS(65),
    [sym__newline] = ACTIONS(63),
  },
  [STATE(8)] = {
    [sym__statement] = STATE(3),
    [sym_block] = STATE(3),
    [sym_assignment] = STATE(3),
    [sym_edge] = STATE(3),
    [sym__path] = STATE(23),
    [sym__path_segment] = STATE(13),
    [sym_string] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_identifier] = ACTIONS(5),
    [sym_comment] = ACTIONS(71),
    [aux_sym_string_token1] = ACTIONS(9),
    [aux_sym_string_token2] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [sym_reserved_word] = ACTIONS(11),
    [sym__newline] = ACTIONS(71),
  },
  [STATE(9)] = {
    [sym__statement] = STATE(3),
    [sym_block] = STATE(3),
    [sym_assignment] = STATE(3),
    [sym_edge] = STATE(3),
    [sym__path] = STATE(23),
    [sym__path_segment] = STATE(13),
    [sym_string] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(73),
    [sym_comment] = ACTIONS(71),
    [aux_sym_string_token1] = ACTIONS(9),
    [aux_sym_string_token2] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [sym_reserved_word] = ACTIONS(11),
    [sym__newline] = ACTIONS(71),
  },
  [STATE(10)] = {
    [sym__statement] = STATE(9),
    [sym_block] = STATE(9),
    [sym_assignment] = STATE(9),
    [sym_edge] = STATE(9),
    [sym__path] = STATE(23),
    [sym__path_segment] = STATE(13),
    [sym_string] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(9),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(75),
    [sym_comment] = ACTIONS(77),
    [aux_sym_string_token1] = ACTIONS(9),
    [aux_sym_string_token2] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [sym_reserved_word] = ACTIONS(11),
    [sym__newline] = ACTIONS(77),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(79), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_comment,
      sym_reserved_word,
      sym__newline,
    ACTIONS(81), 9,
      aux_sym_string_token1,
      aux_sym_string_token2,
      sym_block_string,
      sym_number,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
      sym_unquoted_text,
  [19] = 2,
    ACTIONS(83), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_comment,
      sym_reserved_word,
      sym__newline,
    ACTIONS(85), 9,
      aux_sym_string_token1,
      aux_sym_string_token2,
      sym_block_string,
      sym_number,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
      sym_unquoted_text,
  [38] = 4,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(91), 1,
      anon_sym_DOT,
    STATE(14), 1,
      aux_sym__path_repeat1,
    ACTIONS(87), 10,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_RBRACE,
      sym_comment,
      aux_sym_string_token1,
      aux_sym_string_token2,
      sym_number,
      sym_reserved_word,
      sym_arrow_operator,
      sym__newline,
  [60] = 4,
    ACTIONS(91), 1,
      anon_sym_DOT,
    ACTIONS(95), 1,
      sym_identifier,
    STATE(15), 1,
      aux_sym__path_repeat1,
    ACTIONS(93), 10,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_RBRACE,
      sym_comment,
      aux_sym_string_token1,
      aux_sym_string_token2,
      sym_number,
      sym_reserved_word,
      sym_arrow_operator,
      sym__newline,
  [82] = 4,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 1,
      anon_sym_DOT,
    STATE(15), 1,
      aux_sym__path_repeat1,
    ACTIONS(97), 10,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_RBRACE,
      sym_comment,
      aux_sym_string_token1,
      aux_sym_string_token2,
      sym_number,
      sym_reserved_word,
      sym_arrow_operator,
      sym__newline,
  [104] = 2,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(79), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DOT,
      sym_comment,
      aux_sym_string_token1,
      aux_sym_string_token2,
      sym_number,
      sym_reserved_word,
      sym_arrow_operator,
      sym__newline,
  [121] = 2,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(97), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_RBRACE,
      anon_sym_DOT,
      sym_comment,
      aux_sym_string_token1,
      aux_sym_string_token2,
      sym_number,
      sym_reserved_word,
      sym_arrow_operator,
      sym__newline,
  [138] = 3,
    ACTIONS(106), 1,
      sym_identifier,
    ACTIONS(108), 1,
      anon_sym_COLON,
    ACTIONS(104), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_comment,
      aux_sym_string_token1,
      aux_sym_string_token2,
      sym_number,
      sym_reserved_word,
      sym__newline,
  [155] = 2,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(110), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_comment,
      aux_sym_string_token1,
      aux_sym_string_token2,
      sym_number,
      sym_reserved_word,
      sym__newline,
  [169] = 2,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(114), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_comment,
      aux_sym_string_token1,
      aux_sym_string_token2,
      sym_number,
      sym_reserved_word,
      sym__newline,
  [183] = 5,
    ACTIONS(5), 1,
      sym_identifier,
    STATE(18), 1,
      sym__path,
    ACTIONS(9), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(11), 2,
      sym_number,
      sym_reserved_word,
    STATE(13), 2,
      sym__path_segment,
      sym_string,
  [202] = 4,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(9), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(120), 2,
      sym_number,
      sym_reserved_word,
    STATE(17), 2,
      sym__path_segment,
      sym_string,
  [218] = 2,
    ACTIONS(122), 1,
      anon_sym_COLON,
    ACTIONS(124), 1,
      sym_arrow_operator,
  [225] = 1,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 19,
  [SMALL_STATE(13)] = 38,
  [SMALL_STATE(14)] = 60,
  [SMALL_STATE(15)] = 82,
  [SMALL_STATE(16)] = 104,
  [SMALL_STATE(17)] = 121,
  [SMALL_STATE(18)] = 138,
  [SMALL_STATE(19)] = 155,
  [SMALL_STATE(20)] = 169,
  [SMALL_STATE(21)] = 183,
  [SMALL_STATE(22)] = 202,
  [SMALL_STATE(23)] = 218,
  [SMALL_STATE(24)] = 225,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 2, 0, 1),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge, 5, 0, 2),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_edge, 5, 0, 2),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__value, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__value, 2, 0, 0), SHIFT_REPEAT(5),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__value, 2, 0, 0), SHIFT_REPEAT(11),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__value, 2, 0, 0), SHIFT_REPEAT(12),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__value, 2, 0, 0), SHIFT_REPEAT(5),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 1),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 1),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge, 4, 0, 2),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__path, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__path, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__path, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__path, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__path_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__path_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__path_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_edge, 3, 0, 2),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_edge, 3, 0, 2),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 1),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 5, 0, 1),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 5, 0, 1),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [126] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_d2(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "d2",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
